# Generated by Django 4.1.5 on 2023-01-15 19:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("frontend", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Descripteur",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=256)),
                ("tempsIndexation", models.FloatField(default=0)),
                ("taille", models.FloatField(default=0)),
                ("tempsRecherche", models.FloatField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name="Requete",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("r50", models.FloatField(default=0)),
                ("r100", models.FloatField(default=0)),
                ("rmax", models.FloatField(default=0)),
                ("p50", models.FloatField(default=0)),
                ("p100", models.FloatField(default=0)),
                ("pmax", models.FloatField(default=0)),
                ("ap50", models.FloatField(default=0)),
                ("ap100", models.FloatField(default=0)),
                ("apmax", models.FloatField(default=0)),
                ("map50", models.FloatField(default=0)),
                ("map100", models.FloatField(default=0)),
                ("mapmax", models.FloatField(default=0)),
                (
                    "imageId",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="frontend.inputimage",
                    ),
                ),
            ],
        ),
        migrations.RemoveField(
            model_name="user",
            name="secret_id",
        ),
        migrations.AddField(
            model_name="user",
            name="identifant_secret",
            field=models.CharField(default="", max_length=16),
        ),
        migrations.AddField(
            model_name="user",
            name="isLogged",
            field=models.BooleanField(default=False),
        ),
        migrations.DeleteModel(
            name="Search",
        ),
    ]
