# Generated by Django 4.1.5 on 2023-01-15 20:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("frontend", "0002_descripteur_requete_remove_user_secret_id_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="user",
            old_name="identifant_secret",
            new_name="identifiant_secret",
        ),
    ]
