# Generated by Django 4.1.5 on 2023-01-15 22:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("frontend", "0003_rename_identifant_secret_user_identifiant_secret"),
    ]

    operations = [
        migrations.CreateModel(
            name="Norme",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=250)),
            ],
        ),
        migrations.CreateModel(
            name="Top",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("value", models.IntegerField()),
                ("string", models.CharField(max_length=100)),
            ],
        ),
    ]
