# Generated by Django 4.1.5 on 2023-01-16 10:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("frontend", "0004_norme_top"),
    ]

    operations = [
        migrations.AlterField(
            model_name="descripteur",
            name="name",
            field=models.CharField(max_length=2500),
        ),
        migrations.AlterField(
            model_name="top",
            name="value",
            field=models.IntegerField(default=0),
        ),
    ]
