# Generated by Django 4.1.5 on 2023-01-16 15:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("frontend", "0005_alter_descripteur_name_alter_top_value"),
    ]

    operations = [
        migrations.AddField(
            model_name="requete",
            name="ap20",
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name="requete",
            name="map20",
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name="requete",
            name="p20",
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name="requete",
            name="r20",
            field=models.FloatField(default=0),
        ),
    ]
