# Generated by Django 4.1.5 on 2023-01-16 16:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("frontend", "0006_requete_ap20_requete_map20_requete_p20_requete_r20"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="requete",
            name="imageId",
        ),
        migrations.AddField(
            model_name="requete",
            name="imageName",
            field=models.CharField(default="", max_length=250),
            preserve_default=False,
        ),
    ]
