FROM python:3.7-alpine
COPY requirements.txt requirements.txt
RUN pip install -r requirements.txt
RUN sudo apt-get update
RUN sudo apt-get install ffmpeg libsm6 libxext6  -y
RUN python3 manage.py runserver